HenryCrawfordPoetry/Controllers/AmSoft2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HenryCrawfordPoetry.Controllers
{
    public class AmSoft2Controller : Controller
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
    }
}

HenryCrawfordPoetry/Controllers/PoemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HenryCrawfordPoetry.Controllers
{
    [Authorize]
    public class PoemsController : Controller
    {

        [AllowAnonymous]
        public ActionResult Poem(string fileName)
        {
            ViewBag.PoemFileName = fileName;
            return View();
        }

        [AllowAnonymous]
        public ActionResult PoemTwo(string fileName1, string fileName2)
        {
            ViewBag.PoemFileName1 = fileName1;
            ViewBag.PoemFileName2 = fileName2;
            return View();
        }

        [AllowAnonymous]
        public ActionResult Online()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult AmericanSoftware()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Videos()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult GuestTest()
        {
            return View();
        }        

        [AllowAnonymous]
        public ActionResult WalkingOnACityStreet()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult AmSoft2(string fileName)
        {
            ViewBag.PoemFileName = fileName;
            return View();            
        }
        
    }
}

HenryCrawfordPoetry/Views/AmSoft2/Index.cshtml
@{
    ViewBag.Title = "AmericanSoftware 2.0";
}
    <!-- SECTION -->
    <!-- SECTION -->

    <section class="sct-color-1 slice">
        <div class="container">

            <div class="section-title-wrapper style-1 v1">
                <h3 class="section-title center">
                    <span>American Software 2.0</span>                       
                </h3> 
            </div>

            <div class="row">
                <div class="col-md-9">
                    <div class="block block-image v3 mb-40">
                        <div class="block-image">
                            <img src="~/Images/AmSoft2/Hello_World2.jpg">    
                        </div>
                        <div class="block-content">
                            <h3 class="block-title">
                                Hello World!
                            </h3>
                            <p>
                            When learning a new computer language, a computer programmer will usually write a simple program that displays the text "Hello World." It's the prologue poem in American Software.
                            </p>                                        
                            @Html.ActionLink("Hello World!", "AmSoft2", "Poems", new { fileName="hello_world.html" }, new { @class = "btn btn-sm btn-b-base-1 mt-15" })       
                        </div>
                    </div>

                    <div class="block block-image v3 mb-40">
                        <div class="block-image">
                            <img src="~/Images/AmSoft2/the_orientation_04.13.2011.01.09.38.0.png">                                 
                        </div>
                        <div class="block-content">
                            <h3 class="block-title">
                                The Orientation
                            </h3>
                            <p>
                            American Software 2.0
                            </p>
                            @Html.ActionLink("The Orientation", "AmSoft2", "Poems", new { fileName="the_orientation.html" }, new { @class = "btn btn-sm btn-b-base-1 mt-15" })       
                        </div>
                    </div>

                    <span class="clearfix mt-20"></span>
                                
                    </div>
                <div class="col-md-3">
                    <!-- SIDEBAR -->
            </div>


                </div>

        </div>
    </section>