HenryCrawfordPoetry/Controllers/ToolsController.cs
using Models;
using System;
using System.Text;
using System.Web.Mvc;

namespace HenryCrawfordPoetry.Controllers
{
    public class ToolsController : Controller
    {

        //------------------------------------------------------ Tools Methods ---------------------------------------------------//

        [AllowAnonymous]
        public ActionResult Sestina()
        {
            ViewBag.Message = "Your Sestina Page.";

            SestinaModel sm = new SestinaModel();
            sm.Title = "";

            return View(sm);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSestina(SestinaModel model)
        {
            if (ModelState.IsValid)
            {

                int[,] poem_structure = new int[,]
                {
                  {1, 2, 3, 4, 5, 6},
                  {6, 1, 5, 2, 4, 3},
                  {3, 6, 4, 1, 2, 5},
                  {5, 3, 2, 6, 1, 4},
                  {4, 5, 1, 3, 6, 2},
                  {2, 4, 6, 5, 3, 1}
                };

                StringBuilder sb = new StringBuilder();

                string[] words = new string[]
                {
                    model.LineEnding1,
                    model.LineEnding2,
                    model.LineEnding3,
                    model.LineEnding4,
                    model.LineEnding5,
                    model.LineEnding6
                };

                string pad = "XXXXXXXX";

                sb.Append(model.Title);
                sb.Append(Environment.NewLine);
                sb.Append(Environment.NewLine);

                for (int x = 0; x < poem_structure.GetLength(0); x += 1)
                {
                    for (int y = 0; y < poem_structure.GetLength(1); y += 1)
                    {
                        int index = poem_structure[x, y];
                        sb.Append(pad + " " + words[index - 1]);
                        sb.Append(Environment.NewLine);
                    }

                    sb.Append(Environment.NewLine);
                }


                // http://classicalpoets.org/how-to-write-a-sestina-with-examples/

                // 1    2   3   4   5   6   number order
                // A    B   C   D   E   F   letter order
                // 0    1   2   3   4   5   the 0 based array

                //   (A) F, (B) E, (C) D   from how to write a sestina "circular sestina"
                //    1  6   2  5   3  4    
                //    0  5   1  4   2  3
                //   (A) F, (B) E, (C) D


                // wikipedia: https://en.wikipedia.org/wiki/Sestina
                // 2–5, 4–3, 6–1
                // B E, D C, F A
                // 

                sb.Append(words[0] + " " + words[5]);   // first envoi line

                sb.Append(Environment.NewLine);
                sb.Append(words[1] + " " + words[4]); // second envoi line

                sb.Append(Environment.NewLine);
                sb.Append(words[2] + " " + words[3]); // third envoi line

                string text = sb.ToString();

                Response.Clear();
                Response.ClearHeaders();

                Response.AppendHeader("Content-Length", text.Length.ToString());
                Response.ContentType = "text/plain";
                Response.AppendHeader("Content-Disposition", "attachment;filename=\"sestina_template.txt\"");

                Response.Write(text);
                Response.End();
            }

            // If we got this far, something failed, redisplay form
            return View("Sestina", model);
        }

        [AllowAnonymous]
        public ActionResult Villanelle()
        {
            ViewBag.Message = "Your Villanelle Page.";

            VillanelleModel vm = new VillanelleModel();
            vm.Title = "";
            

            return View(vm);
        }


        // CreateVillanelle
        [HttpPost]
        [AllowAnonymous]
        public ActionResult CreateVillanelle(VillanelleModel vm)
        {
            StringBuilder sb = new StringBuilder();

            sb.Append(vm.Title);
            sb.Append(Environment.NewLine);
            sb.Append(Environment.NewLine);

            sb.Append(vm.Line1);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line2);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line3);

            sb.Append(Environment.NewLine);
            sb.Append(Environment.NewLine);

            sb.Append(vm.Line4);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line5);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line6);

            sb.Append(Environment.NewLine);
            sb.Append(Environment.NewLine);

            sb.Append(vm.Line7);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line8);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line9);

            sb.Append(Environment.NewLine);
            sb.Append(Environment.NewLine);

            sb.Append(vm.Line10);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line11);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line12);

            sb.Append(Environment.NewLine);
            sb.Append(Environment.NewLine);

            sb.Append(vm.Line13);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line14);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line15);

            sb.Append(Environment.NewLine);
            sb.Append(Environment.NewLine);

            sb.Append(vm.Line16);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line17);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line18);
            sb.Append(Environment.NewLine);
            sb.Append(vm.Line19);

            string text = sb.ToString();

            Response.Clear();
            Response.ClearHeaders();

            Response.AppendHeader("Content-Length", text.Length.ToString());
            Response.ContentType = "text/plain";
            Response.AppendHeader("Content-Disposition", "attachment;filename=\"villanelle_template.txt\"");

            Response.Write(text);
            Response.End();

            // If we got this far, something failed, redisplay form
            return View("Villanelle", vm);
        }

                     
        [AllowAnonymous]
        public ActionResult Pantoum()
        {
            ViewBag.Message = "Your Pantoum Page.";

            PantoumModel vm = new PantoumModel();
            vm.Title = "";

            return View(vm);

        }

        // CreatePantoum
        [HttpPost]
        [AllowAnonymous]
        public ActionResult CreatePantoum(PantoumModel pm)
        {
            StringBuilder sb = new StringBuilder();

            sb.Append(pm.Title);
            sb.Append(Environment.NewLine);
            sb.Append(Environment.NewLine);

            sb.Append(pm.PLine1);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine2);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine3);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine4);

            sb.Append(Environment.NewLine);
            sb.Append(Environment.NewLine);

            sb.Append(pm.PLine5);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine6);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine7);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine8);

            sb.Append(Environment.NewLine);
            sb.Append(Environment.NewLine);


            sb.Append(pm.PLine9);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine10);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine11);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine12);

            sb.Append(Environment.NewLine);
            sb.Append(Environment.NewLine);

            sb.Append(pm.PLine13);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine14);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine15);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine16);

            sb.Append(Environment.NewLine);
            sb.Append(Environment.NewLine);

            sb.Append(pm.PLine17);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine18);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine19);
            sb.Append(Environment.NewLine);
            sb.Append(pm.PLine20);


            string text = sb.ToString();

            Response.Clear();
            Response.ClearHeaders();

            Response.AppendHeader("Content-Length", text.Length.ToString());
            Response.ContentType = "text/plain";
            Response.AppendHeader("Content-Disposition", "attachment;filename=\"pantoum_template.txt\"");

            Response.Write(text);
            Response.End();

            // If we got this far, something failed, redisplay form
            return View("Pantoum", pm);
        }



        [AllowAnonymous]
        public ActionResult ManuscriptTemplates()
        {
            ViewBag.Message = "Manuscript Templates";
            return View();
        }


    }
}

HenryCrawfordPoetry/Views/Tools/ManuscriptTemplates.cshtml
@{
    ViewBag.Title = "Manuscript Templates";
}

@section AdditionalMetatags
{
    <meta property="og:url" content="http://henrycrawfordpoetry.com/Tools/ManuscriptTemplates" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Manuscript Templates" />
    <meta property="og:description" content="Download a Word Poetry Template" />
    <meta property="og:image" content="http://henrycrawfordpoetry.com/Images/Website/manuscript_templates.jpg" />
}

<section class="sct-color-1 slice">
    <div class="container">
        <section>


            <div class="row">

                <!-- Default colors -->
                <div class="section-title-wrapper style-1 v1">
                    <h3 class="section-title section-title-sm center">
                        <span>Download a Word Poetry Template</span>
                    </h3>
                </div>

            </div>

            <div class="row">

                <div class="col-md-3">
                    <!-- Post title-->
                    <h2>How to Use the Poetry Templates</h2>
                    <div class="post-meta-top">
                        <div class="embed-responsive embed-responsive-16by9">
                            <iframe width="560" height="315" src="https://www.youtube.com/embed/RfQkYxkWBb4" frameborder="0" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>

                <div class="col-md-8">

                    <p style="padding-top: 30px;">
                        Here are four Word templates which can be used to put together either small poetry submissions or whole manuscripts.
                        The templates use a dynamic table of contents and come in both Calibri and Times New Roman fonts. To use the templates
                        follow the examples inside the templates. For the smaller collection use the Normal style for the poem body and Heading 1 for the poem title.
                        For the manuscript template use the Normal style for poem body, Heading 2 for the poem titles and Heading 1 for the section titles.
                        Once the poems and/or sections are in place, put your cursor in the table of contents and refresh the table by
                        hitting F9 on the keyboard. This will update the pagination and text of the table.
                    </p>




                    <p>
                        If you like the templates or have any questions please <a href="mailto:HenryCrawfordPoetry@gmail.com">send me an email</a> at HenryCrawfordPoetry@gmail.com.
                    </p>

                </div>

            </div>

            <br /><br />

            <div class="row">

                <div class="buttons-example mb-20">
                    @Html.ActionLink("Calibri Template", "DownloadTemplateCalibri", "Home", null, new { @class = "btn btn-blue btn-icon btn-icon-animate fa-pencil-square-o" })
                    @Html.ActionLink("Calibri Manuscript", "DownloadTemplateCalibriManuscript", "Home", null, new { @class = "btn btn-blue btn-icon btn-icon-animate fa-book" })
                    @Html.ActionLink("Times New Roman Template", "DownloadTemplateTimesNewRoman", "Home", null, new { @class = "btn btn-red btn-icon btn-icon-animate fa-pencil-square-o" })
                    @Html.ActionLink("Times New Roman Manuscript", "DownloadTemplateTimesNewRomanManuscript", "Home", null, new { @class = "btn btn-red btn-icon btn-icon-animate fa-book" })
                </div>

            </div>

        </section>
    </div> <!-- .container -->
</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HenryCrawfordPoetry/Views/Tools/Sestina.cshtml
@model Models.SestinaModel

@{
    ViewBag.Title = "Sestinaville";
}

@section AdditionalMetatags
{
    <meta property="og:url" content="http://henrycrawfordpoetry.com/Tools/Sestina" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Sestinaville" />
    <meta property="og:description" content="a tool for writing sestina poems" />
    <meta property="og:image" content="http://henrycrawfordpoetry.com/Images/Website/SestinaVille.png" />
}
   

<section class="sct-color-1 slice">

    <div class="container">

            <div class="row">

                <div class="col-md-3">

                        <div class="section-title-wrapper style-1 v1">
                            <h3 class="section-title left">
                                <span>Sestinaville <small style=" text-transform: lowercase">a tool for writing sestina poems</small></span>
                            </h3> 
                        </div>


                @using (Html.BeginForm("CreateSestina", "Tools"))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
        

                        <div class="form-group">
                            <div class="editor-label">
                                @Html.LabelFor(model => model.Title)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.Title)                    
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="editor-label">
                                @Html.LabelFor(model => model.LineEnding1)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.LineEnding1)<br />
                                @Html.ValidationMessageFor(model => model.LineEnding1)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="editor-label">
                                @Html.LabelFor(model => model.LineEnding2)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.LineEnding2)<br />
                                @Html.ValidationMessageFor(model => model.LineEnding2)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="editor-label">
                                @Html.LabelFor(model => model.LineEnding3)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.LineEnding3)<br />
                                @Html.ValidationMessageFor(model => model.LineEnding3)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="editor-label">
                                @Html.LabelFor(model => model.LineEnding4)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.LineEnding4)<br />
                                @Html.ValidationMessageFor(model => model.LineEnding4)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="editor-label">
                                @Html.LabelFor(model => model.LineEnding5)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.LineEnding5)<br />
                                @Html.ValidationMessageFor(model => model.LineEnding5)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="editor-label">
                                @Html.LabelFor(model => model.LineEnding6)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.LineEnding6)<br />
                                @Html.ValidationMessageFor(model => model.LineEnding6)
                            </div>
                        </div>

                    <br />
                    <p>
                        <button type="submit" class="btn btn-base-1">Create Sestina</button>            
                    </p>
    
                }
        
                </div>        
    
                <div class="col-md-6">

                        <div class="block block-image v2 mb-40">
                            <div class="block-image">                                        
                                <img src="~/Images/Website/SestinaVille.png" alt="Sestinaville" />
                            </div>
                        </div>
                
                        <br />                
                        <p><b>The sestina</b> form is well defined and centers around making a poem of six stanzas each of which consists of six lines. The form dictates that each line end with one of six words that are used throughout the poem. The order of lines in each stanza follows a pattern that can be described algorithmically. So, the first stanza sets the initial order of ending words in lines 1, 2, 3, 4, 5, and 6. The second stanza reorders them as 6, 1, 5, 2, 4, and 3, and this process continues as follows:</p>
                        1, 2, 3, 4, 5, 6, <br />
                        6, 1, 5, 2, 4, 3, <br />
                        3, 6, 4, 1, 2, 5, <br />
                        5, 3, 2, 6, 1, 4, <br />
                        4, 5, 1, 3, 6, 2, <br />
                        2, 4, 6, 5, 3, 1 <br />
                        <br />
                        <p>What Sestinaville allows you to do is concentrate on getting just the six evocative words you need for your poem. You can then enter these words into the form on the webpage as they would appear in the first stanza.: A (line 1), B (line 2), C (line 3), D (line 4), E (line 5) F (line 6). Sestinavile will then write your chosen words into six dummy stanzas that end with the appropriate words. It’s up to you to write the actual lines, but the work of ordering the line endings has been done for you.</p>
                        <p>But that’s not the end of it. After the six stanzas comes the envoi. This is a three line structure that uses all six of the selected words. There are several ways of writing the enovi and the literature suggests a certain freedom here. Sestinaville uses an enovi form as follows:</p>
                        (A) F, (B) E, (C) D <br />
                        or<br />
                        1  6,   2  5,   3  4
                        <br /><br />
                        <p>After you have entered your words in the webpage form (and all six words are required), just hit the button at the bottom of the form. You’ll be prompted to download a text file containing your sestina template. Feel free to do so as many times a you’d like. You can change words and try difference combinations. When you get a text file that you like, just copy it into Word and get to writing the meat of the sestina.</p>

                
                        <ul class="inline-links">
                            <li><a target="_blank" href="http://classicalpoets.org/how-to-write-a-sestina-with-examples/">How to write a sestina with examples</a></li>
                            <li><a target="_blank" href="https://en.wikipedia.org/wiki/Sestina">Wikipedia: Sestina</a></li>                        
                        </ul>                

            </div> <!-- .col-md-6 -->

        </div> <!-- .row-->

    </div> <!-- .container -->

</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}